//! Property-based invariant fuzzing for Soroban contracts.
//!
//! Static analysis answers "does this pattern look wrong?". Fuzzing answers the
//! complement: "can I actually reach a state that breaks a rule the contract
//! promises to keep?". This crate supplies the second half of the toolkit.
//!
//! You describe two things:
//!
//! 1. a [`SystemUnderTest`] — the contract under a test environment, plus a
//!    strategy that generates single calls; and
//! 2. one or more [`Invariant`]s — properties that must hold after *every* call.
//!
//! [`fuzz`] then generates call sequences, runs them, checks the invariants after
//! each step, and uses `proptest`'s shrinking to reduce any failure to the
//! shortest sequence that still breaks it.
//!
//! ## Example
//!
//! ```
//! use soroban_sec_fuzz::{fuzz, invariant, sequence, FuzzConfig, SystemUnderTest};
//! use proptest::prelude::*;
//!
//! #[derive(Debug, Clone)]
//! enum Call {
//!     Deposit { amount: u8 },
//!     Withdraw { amount: u8 },
//! }
//!
//! #[derive(Default)]
//! struct Vault {
//!     balance: i64,
//! }
//!
//! impl SystemUnderTest for Vault {
//!     type Call = Call;
//!
//!     fn execute(&mut self, call: &Call) -> Result<(), String> {
//!         match *call {
//!             Call::Deposit { amount } => self.balance += i64::from(amount),
//!             Call::Withdraw { amount } if self.balance >= i64::from(amount) => {
//!                 self.balance -= i64::from(amount);
//!             }
//!             Call::Withdraw { .. } => return Err("insufficient funds".to_string()),
//!         }
//!         Ok(())
//!     }
//!
//!     fn reset(&mut self) {
//!         self.balance = 0;
//!     }
//! }
//!
//! let calls = || {
//!     let call = prop_oneof![
//!         (1u8..=10).prop_map(|amount| Call::Deposit { amount }),
//!         (1u8..=10).prop_map(|amount| Call::Withdraw { amount }),
//!     ];
//!     sequence(call, 8)
//! };
//!
//! let never_negative = invariant("balance is never negative", |vault: &Vault| {
//!     if vault.balance < 0 {
//!         Err(format!("balance is {}", vault.balance))
//!     } else {
//!         Ok(())
//!     }
//! });
//!
//! let report = fuzz(&FuzzConfig::default(), Vault::default, calls(), &[&never_negative]);
//! assert!(report.is_ok(), "{report}");
//! ```
//!
//! ## Adapting a real contract
//!
//! Implement [`SystemUnderTest`] over `soroban_sdk::Env::default()`: `execute`
//! maps a [`Call`](SystemUnderTest::Call) enum to the generated contract client,
//! and `reset` builds a fresh environment. Invariants then read contract state
//! through the client. See `docs/fuzzing.md` for a full worked adapter.

#![warn(missing_docs)]
#![warn(missing_debug_implementations)]
#![forbid(unsafe_code)]

use std::cell::RefCell;
use std::fmt::Debug;
use std::marker::PhantomData;

use proptest::strategy::Strategy;
use proptest::test_runner::{Config, TestCaseError, TestError, TestRunner};

/// The contract (or system) under test.
///
/// Implement it over the Soroban test environment for a real contract, or over a
/// plain data model in unit tests.
pub trait SystemUnderTest {
    /// A single entrypoint invocation, generated by the test's strategy.
    type Call: Clone + Debug;

    /// Apply one call.
    ///
    /// Return `Err` for an error the contract is *expected* to produce, such as an
    /// authorization failure or a rejected withdrawal. The harness treats it as a
    /// normal outcome and keeps executing the rest of the sequence; a bug is
    /// reported only when an invariant is violated.
    fn execute(&mut self, call: &Self::Call) -> Result<(), String>;

    /// Return the system to a clean initial state before the next sequence.
    fn reset(&mut self);

    /// Render a call for a failure report. Defaults to `Debug`.
    fn describe(call: &Self::Call) -> String {
        format!("{call:?}")
    }
}

/// A property that must hold after every call.
pub trait Invariant<S> {
    /// Human-readable name, used in reports.
    fn name(&self) -> &str;

    /// Check the property. `Err` explains the violation.
    fn check(&self, system: &S) -> Result<(), String>;
}

/// [`Invariant`] implemented from a closure.
#[derive(Debug)]
pub struct FnInvariant<S, F> {
    name: String,
    check: F,
    marker: PhantomData<fn(&S)>,
}

/// Build an invariant from a name and a closure.
///
/// ```
/// use soroban_sec_fuzz::invariant;
///
/// let positive = invariant("stays positive", |value: &i64| {
///     if *value > 0 { Ok(()) } else { Err(format!("{value}")) }
/// });
/// let _ = positive;
/// ```
pub fn invariant<S, F>(name: impl Into<String>, check: F) -> FnInvariant<S, F>
where
    F: Fn(&S) -> Result<(), String>,
{
    FnInvariant {
        name: name.into(),
        check,
        marker: PhantomData,
    }
}

impl<S, F> Invariant<S> for FnInvariant<S, F>
where
    F: Fn(&S) -> Result<(), String>,
{
    fn name(&self) -> &str {
        &self.name
    }

    fn check(&self, system: &S) -> Result<(), String> {
        (self.check)(system)
    }
}

/// How many cases to run and how long each call sequence may be.
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct FuzzConfig {
    /// Number of generated sequences.
    pub cases: u32,
    /// Longest call sequence to generate.
    pub max_calls: usize,
}

impl Default for FuzzConfig {
    fn default() -> Self {
        FuzzConfig {
            cases: 256,
            max_calls: 16,
        }
    }
}

impl FuzzConfig {
    /// Run `cases` sequences of at most `max_calls` calls.
    pub fn new(cases: u32, max_calls: usize) -> Self {
        FuzzConfig { cases, max_calls }
    }
}

/// A single broken invariant, with the call sequence that broke it.
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct Violation {
    /// Name of the invariant that failed.
    pub invariant: String,
    /// Why it failed.
    pub message: String,
    /// The minimal sequence of calls that reproduces the failure.
    pub sequence: Vec<String>,
}

impl std::fmt::Display for Violation {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        writeln!(
            f,
            "invariant `{}` violated: {}",
            self.invariant, self.message
        )?;
        writeln!(f, "minimal sequence ({} call(s)):", self.sequence.len())?;
        for (index, call) in self.sequence.iter().enumerate() {
            writeln!(f, "  {}. {call}", index + 1)?;
        }
        Ok(())
    }
}

/// Outcome of a fuzzing run.
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct FuzzReport {
    /// Number of sequences generated.
    pub cases: u32,
    /// Violations found; empty means the invariants held for every case.
    pub violations: Vec<Violation>,
}

impl FuzzReport {
    /// Whether every generated sequence satisfied every invariant.
    pub fn is_ok(&self) -> bool {
        self.violations.is_empty()
    }

    /// Panic with the minimal reproduction if anything failed.
    ///
    /// ```
    /// # use soroban_sec_fuzz::{fuzz, invariant, sequence, FuzzConfig, SystemUnderTest};
    /// # #[derive(Default)] struct S;
    /// # impl SystemUnderTest for S {
    /// #     type Call = u8;
    /// #     fn execute(&mut self, _: &u8) -> Result<(), String> { Ok(()) }
    /// #     fn reset(&mut self) {}
    /// # }
    /// # let inv = invariant("always holds", |_: &S| Ok(()));
    /// # let calls = sequence(proptest::prelude::Just(0u8), 4);
    /// fuzz(&FuzzConfig::new(32, 4), S::default, calls, &[&inv]).assert_ok();
    /// ```
    pub fn assert_ok(&self) {
        assert!(
            self.is_ok(),
            "invariant fuzzing found {} failure(s):\n{}",
            self.violations.len(),
            self.violations
                .iter()
                .map(Violation::to_string)
                .collect::<String>()
        );
    }
}

impl std::fmt::Display for FuzzReport {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        if self.is_ok() {
            write!(f, "{} case(s), no violations", self.cases)
        } else {
            writeln!(f, "{} violation(s)", self.violations.len())?;
            for violation in &self.violations {
                write!(f, "{violation}")?;
            }
            Ok(())
        }
    }
}

/// A strategy for call sequences of at most `max_calls` calls.
///
/// ```
/// use proptest::prelude::*;
/// use soroban_sec_fuzz::sequence;
///
/// let calls = sequence(any::<u8>(), 4);
/// let _ = calls;
/// ```
pub fn sequence<C>(call: C, max_calls: usize) -> impl Strategy<Value = Vec<C::Value>>
where
    C: Strategy + Clone,
    C::Value: Debug,
{
    proptest::collection::vec(call, 0..=max_calls)
}

/// Generate call sequences, run them against freshly built systems, and check
/// `invariants` after every call.
///
/// On failure the returned [`Violation`] holds the shortest sequence `proptest`
/// could shrink to. A run stops at the first broken invariant.
// `proptest::test_runner::Config` is not constructible with a struct literal from
// outside its crate, so its fields are set on a default instance.
#[allow(clippy::field_reassign_with_default)]
pub fn fuzz<S, B, C>(
    config: &FuzzConfig,
    build: B,
    calls: C,
    invariants: &[&dyn Invariant<S>],
) -> FuzzReport
where
    S: SystemUnderTest,
    B: Fn() -> S,
    C: Strategy<Value = Vec<S::Call>>,
{
    let mut runner_config = Config::default();
    runner_config.cases = config.cases;
    // Library code should not litter the caller's tree with regression files.
    runner_config.failure_persistence = None;
    let mut runner = TestRunner::new(runner_config);

    // `proptest` invokes the test closure repeatedly while shrinking, so keep only
    // the most recent (shortest) failure. The closure must be `Fn`, so a fresh
    // system is built for every generated case.
    let failure: RefCell<Option<Violation>> = RefCell::new(None);

    let outcome = runner.run(&calls, |generated: Vec<S::Call>| {
        let mut system = build();
        system.reset();
        for (index, call) in generated.iter().enumerate() {
            if let Err(reason) = system.execute(call) {
                // A rejected call is a legitimate contract outcome.
                let _ = reason;
                continue;
            }
            for invariant in invariants {
                if let Err(message) = invariant.check(&system) {
                    *failure.borrow_mut() = Some(Violation {
                        invariant: invariant.name().to_string(),
                        message: format!("{message} (at step {})", index + 1),
                        sequence: generated.iter().map(|call| S::describe(call)).collect(),
                    });
                    return Err(TestCaseError::fail(format!(
                        "invariant `{}` violated: {message}",
                        invariant.name()
                    )));
                }
            }
        }
        Ok(())
    });

    let violations = match outcome {
        Ok(()) => Vec::new(),
        Err(TestError::Fail(_, _)) => failure.into_inner().into_iter().collect(),
        Err(other) => vec![Violation {
            invariant: "<runner>".to_string(),
            message: other.to_string(),
            sequence: Vec::new(),
        }],
    };

    FuzzReport {
        cases: config.cases,
        violations,
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use proptest::prelude::*;

    #[derive(Debug, Clone)]
    enum Call {
        Mint { to: u8, amount: u8 },
        Transfer { from: u8, to: u8, amount: u8 },
    }

    struct TokenModel {
        balances: [i64; 2],
        total: i64,
        /// When set, a self-transfer mints instead of moving funds.
        self_transfer_bug: bool,
    }

    impl TokenModel {
        fn new(self_transfer_bug: bool) -> Self {
            TokenModel {
                balances: [0, 0],
                total: 0,
                self_transfer_bug,
            }
        }
    }

    impl SystemUnderTest for TokenModel {
        type Call = Call;

        fn execute(&mut self, call: &Call) -> Result<(), String> {
            match *call {
                Call::Mint { to, amount } => {
                    let to = usize::from(to % 2);
                    self.balances[to] += i64::from(amount);
                    self.total += i64::from(amount);
                }
                Call::Transfer { from, to, amount } => {
                    let from = usize::from(from % 2);
                    let to = usize::from(to % 2);
                    let amount = i64::from(amount);
                    if amount == 0 {
                        return Ok(());
                    }
                    if from == to {
                        if self.self_transfer_bug {
                            self.balances[to] += amount;
                        }
                        return Ok(());
                    }
                    if self.balances[from] < amount {
                        return Err("insufficient balance".to_string());
                    }
                    self.balances[from] -= amount;
                    self.balances[to] += amount;
                }
            }
            Ok(())
        }

        fn reset(&mut self) {
            let bug = self.self_transfer_bug;
            *self = TokenModel::new(bug);
        }
    }

    fn calls() -> impl Strategy<Value = Vec<Call>> {
        let call =
            prop_oneof![
                (any::<u8>(), 1u8..=20).prop_map(|(to, amount)| Call::Mint { to, amount }),
                (any::<u8>(), any::<u8>(), 1u8..=20)
                    .prop_map(|(from, to, amount)| Call::Transfer { from, to, amount }),
            ];
        sequence(call, 8)
    }

    fn conservation() -> impl Invariant<TokenModel> {
        invariant("total supply is conserved", |model: &TokenModel| {
            let sum = model.balances.iter().sum::<i64>();
            if sum == model.total {
                Ok(())
            } else {
                Err(format!("sum(balances)={sum} but total={}", model.total))
            }
        })
    }

    #[test]
    fn healthy_system_satisfies_invariants() {
        let report = fuzz(
            &FuzzConfig::new(128, 8),
            || TokenModel::new(false),
            calls(),
            &[&conservation()],
        );
        assert!(report.is_ok(), "{report}");
        assert_eq!(report.cases, 128);
    }

    #[test]
    fn injected_bug_is_found_and_shrunk() {
        let report = fuzz(
            &FuzzConfig::new(256, 8),
            || TokenModel::new(true),
            calls(),
            &[&conservation()],
        );
        assert!(!report.is_ok(), "the injected bug should have been found");
        let violation = &report.violations[0];
        assert_eq!(violation.invariant, "total supply is conserved");
        // Shrinking should reduce the reproduction to a single self-transfer.
        assert!(
            violation.sequence.len() <= 2,
            "expected a minimal reproduction, got {violation}"
        );
    }

    #[test]
    fn rejected_calls_do_not_fail_a_run() {
        // Withdrawing more than the balance returns Err and must not be reported.
        let report = fuzz(
            &FuzzConfig::new(64, 4),
            || TokenModel::new(false),
            calls(),
            &[&conservation()],
        );
        assert!(report.is_ok());
    }

    #[test]
    fn sequences_respect_the_length_bound() {
        let report = fuzz(
            &FuzzConfig::new(16, 3),
            || TokenModel::new(false),
            calls(),
            &[&conservation()],
        );
        assert!(report.is_ok());
    }

    #[test]
    fn violation_report_includes_the_sequence() {
        let report = fuzz(
            &FuzzConfig::new(256, 8),
            || TokenModel::new(true),
            calls(),
            &[&conservation()],
        );
        let rendered = report.violations[0].to_string();
        assert!(rendered.contains("minimal sequence"));
        assert!(rendered.contains("Transfer"));
    }
}
